import { toPng } from 'html-to-image';

const esc = (s = '') => String(s).replace(/"/g, "'");

/** Architecture → Mermaid flowchart (diagram-as-code). */
export function toMermaid(a) {
  const lines = ['flowchart TD'];
  for (const n of a.nodes) lines.push(`  ${n.id}["${esc(n.label)}${n.tech ? ` — ${esc(n.tech)}` : ''}"]`);
  for (const e of a.edges) {
    const l = esc(e.label);
    if (e.protocol === 'async') lines.push(`  ${e.source} -. ${l} .-> ${e.target}`);
    else if (e.protocol === 'stream') lines.push(`  ${e.source} == ${l} ==> ${e.target}`);
    else lines.push(`  ${e.source} -->|${l}| ${e.target}`);
  }
  return lines.join('\n');
}

/** Full result → Markdown design document. */
export function toDesignDoc(r) {
  const a = r.architecture;
  const label = Object.fromEntries(a.nodes.map((n) => [n.id, n.label]));
  const as = a.assumptions;
  let s = `# ${a.system.name}\n\n${a.system.summary}\n\n`;
  s += `**Domain:** ${a.system.domain} · **Scale:** ${a.system.scale}\n\n`;
  s += `## Assumptions\n- ${as.dailyActiveUsers.toLocaleString()} daily active users, ${as.actionsPerUserPerDay} actions/user/day\n`;
  s += `- Read:Write ${as.readWriteRatio}:1 · avg item ${as.avgItemSizeBytes} B · retention ${as.retentionDays} days\n`;
  s += `- Latency SLO ${as.latencySloMs} ms · ${as.consistency} consistency\n\n`;

  // The derived walkthrough — what makes an exported doc readable by someone
  // who wasn't in the room when the diagram was made.
  const x = r.explanation;
  if (x?.summary || x?.flows?.length) {
    s += `## How it works\n\n`;
    if (x.summary) s += `${x.summary}\n\n`;
    for (const f of x.flows || []) {
      s += `### ${f.title}\n${f.note}\n\n`;
      f.steps.forEach((st, i) => {
        const via = st.via ? ` — *${st.via}*` : '';
        s += `${i + 1}. **${st.label}**${st.tech ? ` (${st.tech})` : ''}${via}\n`;
      });
      s += `\n`;
    }
    if (x.stores?.length) {
      s += `### What each datastore holds\n`;
      for (const st of x.stores) s += `- **${st.label}**${st.tech ? ` (${st.tech})` : ''} — for ${st.role}.\n`;
      s += `\n`;
    }
  }

  s += `## Capacity estimate\n`;
  for (const m of r.capacity.metrics) s += `- **${m.label}:** ${m.value} — ${m.hint}\n`;
  s += `\n## Components\n\n| Layer | Component | Technology | Why |\n|---|---|---|---|\n`;
  for (const n of a.nodes) s += `| ${n.layer} | ${n.label} | ${n.tech || '—'} | ${n.why} |\n`;
  s += `\n## Connections\n\n`;
  for (const e of a.edges) s += `- ${label[e.source]} → ${label[e.target]} — ${e.label} *(${e.protocol})*\n`;
  s += `\n## Production readiness — ${r.readiness.score}/100\n`;
  for (const i of r.readiness.items) s += `- ${i.present ? '✅' : '❌'} ${i.item}\n`;
  s += `\n## Well-Architected review — ${r.review.overall}/100\n`;
  for (const p of r.review.pillars) s += `- **${p.label}:** ${p.score}/100\n`;
  if (a.tradeoffs?.length) {
    s += `\n## Key trade-offs\n`;
    for (const t of a.tradeoffs) s += `- **${t.decision}:** ${t.choice} over ${t.alternative} — ${t.why}\n`;
  }
  if (r.findings?.length) {
    s += `\n## Findings\n`;
    for (const f of r.findings) s += `- \`${f.severity}${f.fixed ? '/fixed' : ''}\` **${f.title}** — ${f.message}\n`;
  }
  s += `\n---\n*Generated by ArchForge — a verified, production-grade system architecture.*\n`;
  return s;
}

export function downloadText(filename, text, mime = 'text/plain') {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function copyText(text) {
  try { await navigator.clipboard.writeText(text); return true; } catch { return false; }
}

/** Export the rendered diagram element as a PNG. */
export async function exportPng(el, name = 'architecture') {
  if (!el) return;
  const bg = getComputedStyle(document.body).getPropertyValue('--bg-inset').trim() || '#0e1116';
  const dataUrl = await toPng(el, { backgroundColor: bg, pixelRatio: 2, cacheBust: true });
  const a = document.createElement('a');
  a.href = dataUrl; a.download = `${name}.png`; a.click();
}

export const slug = (s = 'architecture') => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'architecture';
